# All of this dockerfile is extracted from `./launcher start-cmd`
# DISCOURSE_IMAGE needs to be made with `./launcher bootstrap`
ARG DISCOURSE_IMAGE=local_discourse/default
FROM ${DISCOURSE_IMAGE}

ENV RAILS_ENV=production
ENV UNICORN_WORKERS=3
ENV UNICORN_SIDEKIQS=1
ENV RUBY_GC_HEAP_GROWTH_MAX_SLOTS=40000
ENV RUBY_GC_HEAP_INIT_SLOTS=400000
ENV RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR=1.5

ENV LC_ALL=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8

VOLUME /shared

EXPOSE 80

CMD /sbin/boot
